-- ============================================================================
-- LIGA SOVIET · Datos de la temporada 2025/26
-- ============================================================================
-- GENERADO AUTOMÁTICAMENTE por scripts/generar-migracion-datos.mjs
-- No editar a mano: regenerar el fichero.
--
-- Jugadores: 29  ·  Jornadas: 42
-- Alineaciones: 500  ·  Reservas: 33
--
-- Requiere 0001_esquema_inicial.sql ejecutado antes.
-- Todo va en una transacción: si algo falla, no queda nada a medias.
-- Ejecutarlo dos veces falla por el unique de temporadas.nombre.
-- ============================================================================

begin;

-- Temporada ----------------------------------------------------------------
insert into temporadas (nombre, activa) values ('2025/26', false);

-- Jugadores ----------------------------------------------------------------
insert into jugadores (nombre, pos_principal, pos_secundaria, tipo) values
  ('Adrianskj', 4, 3, 'habitual'),
  ('Santiagovitx', 4, 3, 'habitual'),
  ('Danilov', 2, 1, 'habitual'),
  ('Oriolev', 4, 5, 'habitual'),
  ('Evgeni', 5, 4, 'habitual'),
  ('Gazalov', 3, 2, 'habitual'),
  ('Jasha', null, null, 'habitual'),
  ('Yuri', 1, 2, 'habitual'),
  ('Ladrinskj', 1, 2, 'habitual'),
  ('Machin', 2, 1, 'habitual'),
  ('Germanov', 5, 4, 'habitual'),
  ('Alvarezko', 3, 4, 'habitual'),
  ('Patrikov', null, null, 'invitado'),
  ('Teleskov', 2, 1, 'habitual'),
  ('Stefanov', 4, 3, 'habitual'),
  ('Mijailichenko', 3, 4, 'habitual'),
  ('Vinyalovic', 2, 1, 'habitual'),
  ('Ricky', 4, 5, 'habitual'),
  ('Edu', null, null, 'invitado'),
  ('Davidov', 5, 4, 'habitual'),
  ('Amigo 1', null, null, 'invitado'),
  ('Amigo 2', null, null, 'invitado'),
  ('Manos', null, null, 'invitado'),
  ('Xavi', 2, 3, 'habitual'),
  ('Kostis', 4, 5, 'habitual'),
  ('Toni Primo', null, null, 'invitado'),
  ('Nuevo 2', null, null, 'invitado'),
  ('Nuevo 3', null, null, 'invitado'),
  ('Amigos', null, null, 'invitado');

-- Jornadas -----------------------------------------------------------------
insert into jornadas (temporada_id, numero, estado)
select t.id, v.numero, 'jugada'
from temporadas t, (values
  (1::smallint),
  (2::smallint),
  (4::smallint),
  (5::smallint),
  (6::smallint),
  (7::smallint),
  (8::smallint),
  (9::smallint),
  (10::smallint),
  (11::smallint),
  (12::smallint),
  (13::smallint),
  (14::smallint),
  (15::smallint),
  (16::smallint),
  (17::smallint),
  (18::smallint),
  (19::smallint),
  (20::smallint),
  (21::smallint),
  (22::smallint),
  (23::smallint),
  (24::smallint),
  (25::smallint),
  (26::smallint),
  (27::smallint),
  (28::smallint),
  (29::smallint),
  (30::smallint),
  (31::smallint),
  (32::smallint),
  (33::smallint),
  (34::smallint),
  (35::smallint),
  (36::smallint),
  (37::smallint),
  (38::smallint),
  (39::smallint),
  (40::smallint),
  (41::smallint),
  (42::smallint),
  (43::smallint)
) as v(numero)
where t.nombre = '2025/26';

-- Partidos (uno por jornada; sin marcador: el Excel no lo registraba) -------
insert into partidos (jornada_id, resultado)
select jo.id, v.resultado
from (values
  (1::smallint, 'a'::text),
  (2, 'a'),
  (4, 'empate'),
  (5, 'a'),
  (6, 'a'),
  (7, 'a'),
  (8, 'a'),
  (9, 'a'),
  (10, 'a'),
  (11, 'a'),
  (12, 'a'),
  (13, 'a'),
  (14, 'a'),
  (15, 'a'),
  (16, 'a'),
  (17, 'a'),
  (18, 'a'),
  (19, 'a'),
  (20, 'a'),
  (21, 'a'),
  (22, 'a'),
  (23, 'a'),
  (24, 'a'),
  (25, 'a'),
  (26, 'a'),
  (27, 'a'),
  (28, 'empate'),
  (29, 'a'),
  (30, 'a'),
  (31, 'a'),
  (32, 'a'),
  (33, 'a'),
  (34, 'a'),
  (35, 'a'),
  (36, 'a'),
  (37, 'a'),
  (38, 'a'),
  (39, 'a'),
  (40, 'a'),
  (41, 'a'),
  (42, 'a'),
  (43, 'a')
) as v(numero, resultado)
join temporadas t on t.nombre = '2025/26'
join jornadas jo on jo.temporada_id = t.id and jo.numero = v.numero;

-- Alineaciones: quién jugó de verdad y en qué equipo ------------------------
insert into alineaciones (partido_id, jugador_id, equipo)
select pa.id, ju.id, v.equipo
from (values
  (1::smallint, 'Adrianskj'::text, 'a'::text),
  (1, 'Danilov', 'b'),
  (1, 'Evgeni', 'b'),
  (1, 'Jasha', 'b'),
  (1, 'Yuri', 'a'),
  (1, 'Germanov', 'a'),
  (1, 'Stefanov', 'b'),
  (1, 'Vinyalovic', 'a'),
  (1, 'Ricky', 'a'),
  (1, 'Edu', 'b'),
  (1, 'Xavi', 'a'),
  (1, 'Kostis', 'b'),
  (2, 'Adrianskj', 'a'),
  (2, 'Danilov', 'a'),
  (2, 'Evgeni', 'b'),
  (2, 'Jasha', 'b'),
  (2, 'Yuri', 'b'),
  (2, 'Germanov', 'a'),
  (2, 'Teleskov', 'b'),
  (2, 'Stefanov', 'b'),
  (2, 'Mijailichenko', 'a'),
  (2, 'Vinyalovic', 'a'),
  (2, 'Davidov', 'b'),
  (2, 'Kostis', 'a'),
  (4, 'Adrianskj', null),
  (4, 'Santiagovitx', null),
  (4, 'Oriolev', null),
  (4, 'Evgeni', null),
  (4, 'Ladrinskj', null),
  (4, 'Germanov', null),
  (4, 'Teleskov', null),
  (4, 'Stefanov', null),
  (4, 'Vinyalovic', null),
  (4, 'Ricky', null),
  (4, 'Kostis', null),
  (5, 'Adrianskj', 'b'),
  (5, 'Santiagovitx', 'a'),
  (5, 'Danilov', 'b'),
  (5, 'Oriolev', 'b'),
  (5, 'Ladrinskj', 'a'),
  (5, 'Machin', 'a'),
  (5, 'Alvarezko', 'a'),
  (5, 'Stefanov', 'a'),
  (5, 'Vinyalovic', 'b'),
  (5, 'Ricky', 'b'),
  (5, 'Davidov', 'b'),
  (5, 'Kostis', 'a'),
  (6, 'Adrianskj', 'b'),
  (6, 'Santiagovitx', 'a'),
  (6, 'Danilov', 'b'),
  (6, 'Oriolev', 'b'),
  (6, 'Gazalov', 'a'),
  (6, 'Ladrinskj', 'b'),
  (6, 'Machin', 'a'),
  (6, 'Alvarezko', 'a'),
  (6, 'Teleskov', 'b'),
  (6, 'Vinyalovic', 'b'),
  (6, 'Davidov', 'a'),
  (6, 'Toni Primo', 'a'),
  (7, 'Adrianskj', 'b'),
  (7, 'Santiagovitx', 'a'),
  (7, 'Danilov', 'b'),
  (7, 'Oriolev', 'a'),
  (7, 'Evgeni', 'b'),
  (7, 'Gazalov', 'b'),
  (7, 'Ladrinskj', 'b'),
  (7, 'Machin', 'a'),
  (7, 'Germanov', 'a'),
  (7, 'Alvarezko', 'b'),
  (7, 'Teleskov', 'a'),
  (7, 'Davidov', 'a'),
  (8, 'Adrianskj', 'a'),
  (8, 'Evgeni', 'b'),
  (8, 'Gazalov', 'b'),
  (8, 'Jasha', 'b'),
  (8, 'Yuri', 'a'),
  (8, 'Ladrinskj', 'b'),
  (8, 'Machin', 'a'),
  (8, 'Germanov', 'a'),
  (8, 'Teleskov', 'a'),
  (8, 'Stefanov', 'b'),
  (8, 'Vinyalovic', 'b'),
  (8, 'Ricky', 'a'),
  (9, 'Adrianskj', 'b'),
  (9, 'Santiagovitx', 'a'),
  (9, 'Evgeni', 'a'),
  (9, 'Jasha', 'a'),
  (9, 'Yuri', 'a'),
  (9, 'Machin', 'a'),
  (9, 'Germanov', 'b'),
  (9, 'Alvarezko', 'a'),
  (9, 'Teleskov', 'b'),
  (9, 'Vinyalovic', 'b'),
  (9, 'Ricky', 'b'),
  (9, 'Davidov', 'b'),
  (10, 'Adrianskj', 'b'),
  (10, 'Santiagovitx', 'b'),
  (10, 'Danilov', 'b'),
  (10, 'Oriolev', 'a'),
  (10, 'Evgeni', 'a'),
  (10, 'Gazalov', 'a'),
  (10, 'Yuri', 'a'),
  (10, 'Ladrinskj', 'b'),
  (10, 'Machin', 'b'),
  (10, 'Alvarezko', 'a'),
  (10, 'Stefanov', 'a'),
  (10, 'Davidov', 'b'),
  (11, 'Santiagovitx', 'a'),
  (11, 'Danilov', 'b'),
  (11, 'Oriolev', 'a'),
  (11, 'Evgeni', 'b'),
  (11, 'Gazalov', 'a'),
  (11, 'Yuri', 'a'),
  (11, 'Ladrinskj', 'b'),
  (11, 'Machin', 'b'),
  (11, 'Germanov', 'a'),
  (11, 'Stefanov', 'b'),
  (11, 'Vinyalovic', 'a'),
  (11, 'Ricky', 'b'),
  (12, 'Adrianskj', 'b'),
  (12, 'Danilov', 'a'),
  (12, 'Oriolev', 'b'),
  (12, 'Gazalov', 'a'),
  (12, 'Yuri', 'a'),
  (12, 'Ladrinskj', 'b'),
  (12, 'Machin', 'b'),
  (12, 'Teleskov', 'b'),
  (12, 'Stefanov', 'b'),
  (12, 'Vinyalovic', 'a'),
  (12, 'Ricky', 'a'),
  (12, 'Davidov', 'a'),
  (13, 'Adrianskj', 'b'),
  (13, 'Santiagovitx', 'a'),
  (13, 'Danilov', 'a'),
  (13, 'Oriolev', 'b'),
  (13, 'Evgeni', 'b'),
  (13, 'Yuri', 'b'),
  (13, 'Ladrinskj', 'b'),
  (13, 'Teleskov', 'a'),
  (13, 'Stefanov', 'a'),
  (13, 'Vinyalovic', 'a'),
  (13, 'Ricky', 'b'),
  (13, 'Davidov', 'a'),
  (14, 'Adrianskj', 'b'),
  (14, 'Santiagovitx', 'b'),
  (14, 'Evgeni', 'a'),
  (14, 'Ladrinskj', 'a'),
  (14, 'Machin', 'b'),
  (14, 'Germanov', 'b'),
  (14, 'Alvarezko', 'a'),
  (14, 'Teleskov', 'a'),
  (14, 'Stefanov', 'a'),
  (14, 'Vinyalovic', 'b'),
  (14, 'Ricky', 'a'),
  (15, 'Adrianskj', 'a'),
  (15, 'Santiagovitx', 'a'),
  (15, 'Danilov', 'b'),
  (15, 'Oriolev', 'b'),
  (15, 'Evgeni', 'b'),
  (15, 'Gazalov', 'a'),
  (15, 'Yuri', 'b'),
  (15, 'Machin', 'b'),
  (15, 'Germanov', 'a'),
  (15, 'Teleskov', 'a'),
  (15, 'Stefanov', 'b'),
  (16, 'Adrianskj', 'b'),
  (16, 'Santiagovitx', 'a'),
  (16, 'Oriolev', 'b'),
  (16, 'Evgeni', 'a'),
  (16, 'Yuri', 'a'),
  (16, 'Ladrinskj', 'a'),
  (16, 'Machin', 'a'),
  (16, 'Germanov', 'b'),
  (16, 'Alvarezko', 'b'),
  (16, 'Teleskov', 'b'),
  (16, 'Ricky', 'a'),
  (16, 'Edu', 'b'),
  (17, 'Adrianskj', 'b'),
  (17, 'Santiagovitx', 'a'),
  (17, 'Danilov', 'a'),
  (17, 'Oriolev', 'b'),
  (17, 'Gazalov', 'b'),
  (17, 'Yuri', 'b'),
  (17, 'Ladrinskj', 'a'),
  (17, 'Machin', 'b'),
  (17, 'Alvarezko', 'a'),
  (17, 'Teleskov', 'a'),
  (17, 'Ricky', 'a'),
  (17, 'Toni Primo', 'b'),
  (18, 'Adrianskj', 'b'),
  (18, 'Santiagovitx', 'b'),
  (18, 'Danilov', 'a'),
  (18, 'Gazalov', 'a'),
  (18, 'Yuri', 'a'),
  (18, 'Ladrinskj', 'b'),
  (18, 'Machin', 'b'),
  (18, 'Germanov', 'b'),
  (18, 'Alvarezko', 'a'),
  (18, 'Teleskov', 'b'),
  (18, 'Stefanov', 'a'),
  (18, 'Ricky', 'a'),
  (19, 'Adrianskj', 'b'),
  (19, 'Santiagovitx', 'a'),
  (19, 'Danilov', 'b'),
  (19, 'Oriolev', 'b'),
  (19, 'Evgeni', 'b'),
  (19, 'Gazalov', 'b'),
  (19, 'Yuri', 'b'),
  (19, 'Ladrinskj', 'a'),
  (19, 'Germanov', 'a'),
  (19, 'Teleskov', 'a'),
  (19, 'Stefanov', 'a'),
  (19, 'Ricky', 'a'),
  (20, 'Adrianskj', 'b'),
  (20, 'Santiagovitx', 'b'),
  (20, 'Danilov', 'a'),
  (20, 'Evgeni', 'b'),
  (20, 'Gazalov', 'a'),
  (20, 'Yuri', 'a'),
  (20, 'Ladrinskj', 'b'),
  (20, 'Machin', 'b'),
  (20, 'Alvarezko', 'a'),
  (20, 'Stefanov', 'b'),
  (20, 'Mijailichenko', 'a'),
  (20, 'Ricky', 'a'),
  (21, 'Adrianskj', 'a'),
  (21, 'Santiagovitx', 'b'),
  (21, 'Danilov', 'a'),
  (21, 'Evgeni', 'b'),
  (21, 'Ladrinskj', 'b'),
  (21, 'Machin', 'a'),
  (21, 'Germanov', 'a'),
  (21, 'Alvarezko', 'a'),
  (21, 'Teleskov', 'a'),
  (21, 'Stefanov', 'b'),
  (21, 'Vinyalovic', 'b'),
  (21, 'Ricky', 'b'),
  (22, 'Santiagovitx', 'b'),
  (22, 'Danilov', 'b'),
  (22, 'Evgeni', 'b'),
  (22, 'Gazalov', 'a'),
  (22, 'Yuri', 'a'),
  (22, 'Machin', 'b'),
  (22, 'Germanov', 'a'),
  (22, 'Alvarezko', 'b'),
  (22, 'Teleskov', 'b'),
  (22, 'Vinyalovic', 'a'),
  (22, 'Ricky', 'a'),
  (22, 'Kostis', 'a'),
  (23, 'Adrianskj', 'a'),
  (23, 'Santiagovitx', 'b'),
  (23, 'Danilov', 'a'),
  (23, 'Evgeni', 'b'),
  (23, 'Gazalov', 'b'),
  (23, 'Yuri', 'b'),
  (23, 'Machin', 'b'),
  (23, 'Germanov', 'a'),
  (23, 'Teleskov', 'a'),
  (23, 'Stefanov', 'a'),
  (23, 'Vinyalovic', 'a'),
  (23, 'Ricky', 'b'),
  (24, 'Danilov', 'b'),
  (24, 'Oriolev', 'b'),
  (24, 'Evgeni', 'a'),
  (24, 'Gazalov', 'a'),
  (24, 'Yuri', 'a'),
  (24, 'Ladrinskj', 'a'),
  (24, 'Machin', 'a'),
  (24, 'Germanov', 'b'),
  (24, 'Alvarezko', 'a'),
  (24, 'Teleskov', 'b'),
  (24, 'Ricky', 'b'),
  (24, 'Toni Primo', 'b'),
  (25, 'Adrianskj', 'a'),
  (25, 'Danilov', 'b'),
  (25, 'Oriolev', 'b'),
  (25, 'Evgeni', 'a'),
  (25, 'Gazalov', 'a'),
  (25, 'Ladrinskj', 'a'),
  (25, 'Germanov', 'b'),
  (25, 'Alvarezko', 'a'),
  (25, 'Teleskov', 'b'),
  (25, 'Stefanov', 'b'),
  (25, 'Vinyalovic', 'b'),
  (25, 'Ricky', 'a'),
  (26, 'Danilov', 'a'),
  (26, 'Oriolev', 'b'),
  (26, 'Evgeni', 'a'),
  (26, 'Yuri', 'b'),
  (26, 'Ladrinskj', 'b'),
  (26, 'Machin', 'b'),
  (26, 'Germanov', 'b'),
  (26, 'Alvarezko', 'a'),
  (26, 'Teleskov', 'a'),
  (26, 'Stefanov', 'b'),
  (26, 'Vinyalovic', 'a'),
  (26, 'Ricky', 'a'),
  (27, 'Santiagovitx', 'a'),
  (27, 'Oriolev', 'a'),
  (27, 'Evgeni', 'b'),
  (27, 'Gazalov', 'a'),
  (27, 'Yuri', 'a'),
  (27, 'Ladrinskj', 'b'),
  (27, 'Machin', 'b'),
  (27, 'Alvarezko', 'b'),
  (27, 'Teleskov', 'a'),
  (27, 'Stefanov', 'b'),
  (27, 'Vinyalovic', 'b'),
  (27, 'Ricky', 'a'),
  (28, 'Danilov', null),
  (28, 'Evgeni', null),
  (28, 'Gazalov', null),
  (28, 'Jasha', null),
  (28, 'Yuri', null),
  (28, 'Ladrinskj', null),
  (28, 'Germanov', null),
  (28, 'Alvarezko', null),
  (28, 'Teleskov', null),
  (28, 'Ricky', null),
  (28, 'Davidov', null),
  (29, 'Adrianskj', 'a'),
  (29, 'Danilov', 'a'),
  (29, 'Oriolev', 'a'),
  (29, 'Yuri', 'a'),
  (29, 'Ladrinskj', 'b'),
  (29, 'Machin', 'b'),
  (29, 'Germanov', 'a'),
  (29, 'Alvarezko', 'b'),
  (29, 'Teleskov', 'a'),
  (29, 'Stefanov', 'b'),
  (29, 'Ricky', 'b'),
  (29, 'Xavi', 'b'),
  (30, 'Adrianskj', 'a'),
  (30, 'Danilov', 'a'),
  (30, 'Oriolev', 'b'),
  (30, 'Gazalov', 'b'),
  (30, 'Jasha', 'b'),
  (30, 'Yuri', 'b'),
  (30, 'Ladrinskj', 'b'),
  (30, 'Machin', 'a'),
  (30, 'Teleskov', 'a'),
  (30, 'Vinyalovic', 'b'),
  (30, 'Ricky', 'a'),
  (30, 'Xavi', 'a'),
  (31, 'Adrianskj', 'a'),
  (31, 'Santiagovitx', 'b'),
  (31, 'Danilov', 'a'),
  (31, 'Oriolev', 'a'),
  (31, 'Gazalov', 'a'),
  (31, 'Yuri', 'a'),
  (31, 'Ladrinskj', 'b'),
  (31, 'Germanov', 'b'),
  (31, 'Teleskov', 'a'),
  (31, 'Stefanov', 'b'),
  (31, 'Mijailichenko', 'b'),
  (31, 'Vinyalovic', 'b'),
  (32, 'Adrianskj', 'b'),
  (32, 'Santiagovitx', 'a'),
  (32, 'Danilov', 'a'),
  (32, 'Gazalov', 'a'),
  (32, 'Yuri', 'b'),
  (32, 'Machin', 'a'),
  (32, 'Teleskov', 'a'),
  (32, 'Stefanov', 'b'),
  (32, 'Mijailichenko', 'b'),
  (32, 'Vinyalovic', 'b'),
  (32, 'Davidov', 'a'),
  (32, 'Xavi', 'b'),
  (33, 'Adrianskj', 'b'),
  (33, 'Danilov', 'b'),
  (33, 'Yuri', 'a'),
  (33, 'Ladrinskj', 'b'),
  (33, 'Machin', 'b'),
  (33, 'Germanov', 'a'),
  (33, 'Alvarezko', 'a'),
  (33, 'Teleskov', 'b'),
  (33, 'Stefanov', 'a'),
  (33, 'Vinyalovic', 'a'),
  (33, 'Ricky', 'b'),
  (33, 'Xavi', 'a'),
  (34, 'Adrianskj', 'a'),
  (34, 'Santiagovitx', 'a'),
  (34, 'Danilov', 'b'),
  (34, 'Oriolev', 'b'),
  (34, 'Gazalov', 'a'),
  (34, 'Jasha', 'b'),
  (34, 'Yuri', 'a'),
  (34, 'Ladrinskj', 'b'),
  (34, 'Stefanov', 'b'),
  (34, 'Vinyalovic', 'b'),
  (34, 'Ricky', 'a'),
  (34, 'Xavi', 'a'),
  (35, 'Adrianskj', 'a'),
  (35, 'Danilov', 'b'),
  (35, 'Oriolev', 'a'),
  (35, 'Evgeni', 'b'),
  (35, 'Jasha', 'a'),
  (35, 'Yuri', 'b'),
  (35, 'Ladrinskj', 'a'),
  (35, 'Machin', 'a'),
  (35, 'Alvarezko', 'b'),
  (35, 'Teleskov', 'a'),
  (35, 'Vinyalovic', 'b'),
  (35, 'Ricky', 'b'),
  (36, 'Santiagovitx', 'a'),
  (36, 'Oriolev', 'a'),
  (36, 'Evgeni', 'a'),
  (36, 'Gazalov', 'b'),
  (36, 'Ladrinskj', 'b'),
  (36, 'Machin', 'a'),
  (36, 'Germanov', 'b'),
  (36, 'Alvarezko', 'a'),
  (36, 'Teleskov', 'a'),
  (36, 'Stefanov', 'b'),
  (36, 'Vinyalovic', 'b'),
  (36, 'Xavi', 'b'),
  (37, 'Adrianskj', 'a'),
  (37, 'Santiagovitx', 'b'),
  (37, 'Danilov', 'a'),
  (37, 'Evgeni', 'a'),
  (37, 'Jasha', 'b'),
  (37, 'Yuri', 'b'),
  (37, 'Ladrinskj', 'a'),
  (37, 'Machin', 'b'),
  (37, 'Germanov', 'b'),
  (37, 'Stefanov', 'a'),
  (37, 'Ricky', 'a'),
  (37, 'Davidov', 'b'),
  (38, 'Santiagovitx', 'a'),
  (38, 'Danilov', 'b'),
  (38, 'Evgeni', 'b'),
  (38, 'Gazalov', 'a'),
  (38, 'Jasha', 'b'),
  (38, 'Yuri', 'b'),
  (38, 'Ladrinskj', 'a'),
  (38, 'Teleskov', 'a'),
  (38, 'Stefanov', 'b'),
  (38, 'Mijailichenko', 'a'),
  (38, 'Ricky', 'a'),
  (38, 'Xavi', 'b'),
  (39, 'Adrianskj', 'a'),
  (39, 'Santiagovitx', 'a'),
  (39, 'Gazalov', 'a'),
  (39, 'Jasha', 'b'),
  (39, 'Yuri', 'a'),
  (39, 'Ladrinskj', 'b'),
  (39, 'Machin', 'a'),
  (39, 'Germanov', 'a'),
  (39, 'Stefanov', 'b'),
  (39, 'Ricky', 'b'),
  (39, 'Xavi', 'b'),
  (39, 'Amigos', 'b'),
  (40, 'Adrianskj', 'a'),
  (40, 'Santiagovitx', 'b'),
  (40, 'Danilov', 'a'),
  (40, 'Gazalov', 'b'),
  (40, 'Yuri', 'a'),
  (40, 'Ladrinskj', 'b'),
  (40, 'Machin', 'a'),
  (40, 'Germanov', 'a'),
  (40, 'Alvarezko', 'b'),
  (40, 'Stefanov', 'b'),
  (40, 'Vinyalovic', 'a'),
  (40, 'Ricky', 'b'),
  (41, 'Adrianskj', 'b'),
  (41, 'Danilov', 'b'),
  (41, 'Oriolev', 'a'),
  (41, 'Jasha', 'a'),
  (41, 'Yuri', 'a'),
  (41, 'Ladrinskj', 'b'),
  (41, 'Machin', 'b'),
  (41, 'Germanov', 'a'),
  (41, 'Teleskov', 'b'),
  (41, 'Vinyalovic', 'a'),
  (41, 'Ricky', 'b'),
  (41, 'Xavi', 'a'),
  (42, 'Adrianskj', 'a'),
  (42, 'Danilov', 'b'),
  (42, 'Evgeni', 'b'),
  (42, 'Gazalov', 'b'),
  (42, 'Jasha', 'a'),
  (42, 'Yuri', 'b'),
  (42, 'Ladrinskj', 'b'),
  (42, 'Machin', 'a'),
  (42, 'Teleskov', 'a'),
  (42, 'Vinyalovic', 'a'),
  (42, 'Ricky', 'b'),
  (42, 'Xavi', 'a'),
  (43, 'Adrianskj', 'a'),
  (43, 'Danilov', 'b'),
  (43, 'Evgeni', 'b'),
  (43, 'Gazalov', 'b'),
  (43, 'Jasha', 'a'),
  (43, 'Yuri', 'b'),
  (43, 'Ladrinskj', 'b'),
  (43, 'Machin', 'a'),
  (43, 'Teleskov', 'a'),
  (43, 'Vinyalovic', 'a'),
  (43, 'Ricky', 'b'),
  (43, 'Xavi', 'a')
) as v(jornada, nombre, equipo)
join temporadas t on t.nombre = '2025/26'
join jornadas jo on jo.temporada_id = t.id and jo.numero = v.jornada
join partidos pa on pa.jornada_id = jo.id
join jugadores ju on ju.nombre = v.nombre;

-- Convocatorias: lo previsto (titulares + reservas) -------------------------
insert into convocatorias (jornada_id, jugador_id, rol)
select jo.id, ju.id, v.rol
from (values
  (1::smallint, 'Adrianskj'::text, 'titular'::text),
  (1, 'Danilov', 'titular'),
  (1, 'Evgeni', 'titular'),
  (1, 'Jasha', 'titular'),
  (1, 'Yuri', 'titular'),
  (1, 'Germanov', 'titular'),
  (1, 'Stefanov', 'titular'),
  (1, 'Vinyalovic', 'titular'),
  (1, 'Ricky', 'titular'),
  (1, 'Edu', 'titular'),
  (1, 'Xavi', 'titular'),
  (1, 'Kostis', 'titular'),
  (2, 'Adrianskj', 'titular'),
  (2, 'Danilov', 'titular'),
  (2, 'Evgeni', 'titular'),
  (2, 'Jasha', 'titular'),
  (2, 'Yuri', 'titular'),
  (2, 'Germanov', 'titular'),
  (2, 'Teleskov', 'titular'),
  (2, 'Stefanov', 'titular'),
  (2, 'Mijailichenko', 'titular'),
  (2, 'Vinyalovic', 'titular'),
  (2, 'Davidov', 'titular'),
  (2, 'Kostis', 'titular'),
  (4, 'Adrianskj', 'titular'),
  (4, 'Santiagovitx', 'titular'),
  (4, 'Oriolev', 'titular'),
  (4, 'Evgeni', 'titular'),
  (4, 'Ladrinskj', 'titular'),
  (4, 'Germanov', 'titular'),
  (4, 'Teleskov', 'titular'),
  (4, 'Stefanov', 'titular'),
  (4, 'Vinyalovic', 'titular'),
  (4, 'Ricky', 'titular'),
  (4, 'Kostis', 'titular'),
  (5, 'Adrianskj', 'titular'),
  (5, 'Santiagovitx', 'titular'),
  (5, 'Danilov', 'titular'),
  (5, 'Oriolev', 'titular'),
  (5, 'Ladrinskj', 'titular'),
  (5, 'Machin', 'titular'),
  (5, 'Alvarezko', 'titular'),
  (5, 'Stefanov', 'titular'),
  (5, 'Vinyalovic', 'titular'),
  (5, 'Ricky', 'titular'),
  (5, 'Davidov', 'titular'),
  (5, 'Kostis', 'titular'),
  (6, 'Adrianskj', 'titular'),
  (6, 'Santiagovitx', 'titular'),
  (6, 'Danilov', 'titular'),
  (6, 'Oriolev', 'titular'),
  (6, 'Gazalov', 'titular'),
  (6, 'Ladrinskj', 'titular'),
  (6, 'Machin', 'titular'),
  (6, 'Alvarezko', 'titular'),
  (6, 'Teleskov', 'titular'),
  (6, 'Vinyalovic', 'titular'),
  (6, 'Davidov', 'titular'),
  (6, 'Toni Primo', 'titular'),
  (7, 'Adrianskj', 'titular'),
  (7, 'Santiagovitx', 'titular'),
  (7, 'Danilov', 'titular'),
  (7, 'Oriolev', 'titular'),
  (7, 'Evgeni', 'titular'),
  (7, 'Gazalov', 'titular'),
  (7, 'Ladrinskj', 'titular'),
  (7, 'Machin', 'titular'),
  (7, 'Germanov', 'titular'),
  (7, 'Alvarezko', 'titular'),
  (7, 'Teleskov', 'titular'),
  (7, 'Davidov', 'titular'),
  (7, 'Vinyalovic', 'reserva'),
  (8, 'Adrianskj', 'titular'),
  (8, 'Evgeni', 'titular'),
  (8, 'Gazalov', 'titular'),
  (8, 'Jasha', 'titular'),
  (8, 'Yuri', 'titular'),
  (8, 'Ladrinskj', 'titular'),
  (8, 'Machin', 'titular'),
  (8, 'Germanov', 'titular'),
  (8, 'Teleskov', 'titular'),
  (8, 'Stefanov', 'titular'),
  (8, 'Vinyalovic', 'titular'),
  (8, 'Ricky', 'titular'),
  (8, 'Danilov', 'reserva'),
  (8, 'Oriolev', 'reserva'),
  (8, 'Davidov', 'reserva'),
  (9, 'Adrianskj', 'titular'),
  (9, 'Santiagovitx', 'titular'),
  (9, 'Evgeni', 'titular'),
  (9, 'Jasha', 'titular'),
  (9, 'Yuri', 'titular'),
  (9, 'Machin', 'titular'),
  (9, 'Germanov', 'titular'),
  (9, 'Alvarezko', 'titular'),
  (9, 'Teleskov', 'titular'),
  (9, 'Vinyalovic', 'titular'),
  (9, 'Ricky', 'titular'),
  (9, 'Davidov', 'titular'),
  (9, 'Ladrinskj', 'reserva'),
  (10, 'Adrianskj', 'titular'),
  (10, 'Santiagovitx', 'titular'),
  (10, 'Danilov', 'titular'),
  (10, 'Oriolev', 'titular'),
  (10, 'Evgeni', 'titular'),
  (10, 'Gazalov', 'titular'),
  (10, 'Yuri', 'titular'),
  (10, 'Ladrinskj', 'titular'),
  (10, 'Machin', 'titular'),
  (10, 'Alvarezko', 'titular'),
  (10, 'Stefanov', 'titular'),
  (10, 'Davidov', 'titular'),
  (10, 'Germanov', 'reserva'),
  (11, 'Santiagovitx', 'titular'),
  (11, 'Danilov', 'titular'),
  (11, 'Oriolev', 'titular'),
  (11, 'Evgeni', 'titular'),
  (11, 'Gazalov', 'titular'),
  (11, 'Yuri', 'titular'),
  (11, 'Ladrinskj', 'titular'),
  (11, 'Machin', 'titular'),
  (11, 'Germanov', 'titular'),
  (11, 'Stefanov', 'titular'),
  (11, 'Vinyalovic', 'titular'),
  (11, 'Ricky', 'titular'),
  (11, 'Adrianskj', 'reserva'),
  (11, 'Alvarezko', 'reserva'),
  (11, 'Teleskov', 'reserva'),
  (12, 'Adrianskj', 'titular'),
  (12, 'Danilov', 'titular'),
  (12, 'Oriolev', 'titular'),
  (12, 'Gazalov', 'titular'),
  (12, 'Yuri', 'titular'),
  (12, 'Ladrinskj', 'titular'),
  (12, 'Machin', 'titular'),
  (12, 'Teleskov', 'titular'),
  (12, 'Stefanov', 'titular'),
  (12, 'Vinyalovic', 'titular'),
  (12, 'Ricky', 'titular'),
  (12, 'Davidov', 'titular'),
  (12, 'Santiagovitx', 'reserva'),
  (12, 'Evgeni', 'reserva'),
  (13, 'Adrianskj', 'titular'),
  (13, 'Santiagovitx', 'titular'),
  (13, 'Danilov', 'titular'),
  (13, 'Oriolev', 'titular'),
  (13, 'Evgeni', 'titular'),
  (13, 'Yuri', 'titular'),
  (13, 'Ladrinskj', 'titular'),
  (13, 'Teleskov', 'titular'),
  (13, 'Stefanov', 'titular'),
  (13, 'Vinyalovic', 'titular'),
  (13, 'Ricky', 'titular'),
  (13, 'Davidov', 'titular'),
  (14, 'Adrianskj', 'titular'),
  (14, 'Santiagovitx', 'titular'),
  (14, 'Evgeni', 'titular'),
  (14, 'Ladrinskj', 'titular'),
  (14, 'Machin', 'titular'),
  (14, 'Germanov', 'titular'),
  (14, 'Alvarezko', 'titular'),
  (14, 'Teleskov', 'titular'),
  (14, 'Stefanov', 'titular'),
  (14, 'Vinyalovic', 'titular'),
  (14, 'Ricky', 'titular'),
  (15, 'Adrianskj', 'titular'),
  (15, 'Santiagovitx', 'titular'),
  (15, 'Danilov', 'titular'),
  (15, 'Oriolev', 'titular'),
  (15, 'Evgeni', 'titular'),
  (15, 'Gazalov', 'titular'),
  (15, 'Yuri', 'titular'),
  (15, 'Machin', 'titular'),
  (15, 'Germanov', 'titular'),
  (15, 'Teleskov', 'titular'),
  (15, 'Stefanov', 'titular'),
  (16, 'Adrianskj', 'titular'),
  (16, 'Santiagovitx', 'titular'),
  (16, 'Oriolev', 'titular'),
  (16, 'Evgeni', 'titular'),
  (16, 'Yuri', 'titular'),
  (16, 'Ladrinskj', 'titular'),
  (16, 'Machin', 'titular'),
  (16, 'Germanov', 'titular'),
  (16, 'Alvarezko', 'titular'),
  (16, 'Teleskov', 'titular'),
  (16, 'Ricky', 'titular'),
  (16, 'Edu', 'titular'),
  (17, 'Adrianskj', 'titular'),
  (17, 'Santiagovitx', 'titular'),
  (17, 'Danilov', 'titular'),
  (17, 'Oriolev', 'titular'),
  (17, 'Gazalov', 'titular'),
  (17, 'Yuri', 'titular'),
  (17, 'Ladrinskj', 'titular'),
  (17, 'Machin', 'titular'),
  (17, 'Alvarezko', 'titular'),
  (17, 'Teleskov', 'titular'),
  (17, 'Ricky', 'titular'),
  (17, 'Toni Primo', 'titular'),
  (18, 'Adrianskj', 'titular'),
  (18, 'Santiagovitx', 'titular'),
  (18, 'Danilov', 'titular'),
  (18, 'Gazalov', 'titular'),
  (18, 'Yuri', 'titular'),
  (18, 'Ladrinskj', 'titular'),
  (18, 'Machin', 'titular'),
  (18, 'Germanov', 'titular'),
  (18, 'Alvarezko', 'titular'),
  (18, 'Teleskov', 'titular'),
  (18, 'Stefanov', 'titular'),
  (18, 'Ricky', 'titular'),
  (18, 'Evgeni', 'reserva'),
  (19, 'Adrianskj', 'titular'),
  (19, 'Santiagovitx', 'titular'),
  (19, 'Danilov', 'titular'),
  (19, 'Oriolev', 'titular'),
  (19, 'Evgeni', 'titular'),
  (19, 'Gazalov', 'titular'),
  (19, 'Yuri', 'titular'),
  (19, 'Ladrinskj', 'titular'),
  (19, 'Germanov', 'titular'),
  (19, 'Teleskov', 'titular'),
  (19, 'Stefanov', 'titular'),
  (19, 'Ricky', 'titular'),
  (20, 'Adrianskj', 'titular'),
  (20, 'Santiagovitx', 'titular'),
  (20, 'Danilov', 'titular'),
  (20, 'Evgeni', 'titular'),
  (20, 'Gazalov', 'titular'),
  (20, 'Yuri', 'titular'),
  (20, 'Ladrinskj', 'titular'),
  (20, 'Machin', 'titular'),
  (20, 'Alvarezko', 'titular'),
  (20, 'Stefanov', 'titular'),
  (20, 'Mijailichenko', 'titular'),
  (20, 'Ricky', 'titular'),
  (20, 'Teleskov', 'reserva'),
  (20, 'Vinyalovic', 'reserva'),
  (21, 'Adrianskj', 'titular'),
  (21, 'Santiagovitx', 'titular'),
  (21, 'Danilov', 'titular'),
  (21, 'Evgeni', 'titular'),
  (21, 'Ladrinskj', 'titular'),
  (21, 'Machin', 'titular'),
  (21, 'Germanov', 'titular'),
  (21, 'Alvarezko', 'titular'),
  (21, 'Teleskov', 'titular'),
  (21, 'Stefanov', 'titular'),
  (21, 'Vinyalovic', 'titular'),
  (21, 'Ricky', 'titular'),
  (22, 'Santiagovitx', 'titular'),
  (22, 'Danilov', 'titular'),
  (22, 'Evgeni', 'titular'),
  (22, 'Gazalov', 'titular'),
  (22, 'Yuri', 'titular'),
  (22, 'Machin', 'titular'),
  (22, 'Germanov', 'titular'),
  (22, 'Alvarezko', 'titular'),
  (22, 'Teleskov', 'titular'),
  (22, 'Vinyalovic', 'titular'),
  (22, 'Ricky', 'titular'),
  (22, 'Kostis', 'titular'),
  (23, 'Adrianskj', 'titular'),
  (23, 'Santiagovitx', 'titular'),
  (23, 'Danilov', 'titular'),
  (23, 'Evgeni', 'titular'),
  (23, 'Gazalov', 'titular'),
  (23, 'Yuri', 'titular'),
  (23, 'Machin', 'titular'),
  (23, 'Germanov', 'titular'),
  (23, 'Teleskov', 'titular'),
  (23, 'Stefanov', 'titular'),
  (23, 'Vinyalovic', 'titular'),
  (23, 'Ricky', 'titular'),
  (24, 'Danilov', 'titular'),
  (24, 'Oriolev', 'titular'),
  (24, 'Evgeni', 'titular'),
  (24, 'Gazalov', 'titular'),
  (24, 'Yuri', 'titular'),
  (24, 'Ladrinskj', 'titular'),
  (24, 'Machin', 'titular'),
  (24, 'Germanov', 'titular'),
  (24, 'Alvarezko', 'titular'),
  (24, 'Teleskov', 'titular'),
  (24, 'Ricky', 'titular'),
  (24, 'Toni Primo', 'titular'),
  (25, 'Adrianskj', 'titular'),
  (25, 'Danilov', 'titular'),
  (25, 'Oriolev', 'titular'),
  (25, 'Evgeni', 'titular'),
  (25, 'Gazalov', 'titular'),
  (25, 'Ladrinskj', 'titular'),
  (25, 'Germanov', 'titular'),
  (25, 'Alvarezko', 'titular'),
  (25, 'Teleskov', 'titular'),
  (25, 'Stefanov', 'titular'),
  (25, 'Vinyalovic', 'titular'),
  (25, 'Ricky', 'titular'),
  (25, 'Yuri', 'reserva'),
  (25, 'Machin', 'reserva'),
  (26, 'Danilov', 'titular'),
  (26, 'Oriolev', 'titular'),
  (26, 'Evgeni', 'titular'),
  (26, 'Yuri', 'titular'),
  (26, 'Ladrinskj', 'titular'),
  (26, 'Machin', 'titular'),
  (26, 'Germanov', 'titular'),
  (26, 'Alvarezko', 'titular'),
  (26, 'Teleskov', 'titular'),
  (26, 'Stefanov', 'titular'),
  (26, 'Vinyalovic', 'titular'),
  (26, 'Ricky', 'titular'),
  (27, 'Santiagovitx', 'titular'),
  (27, 'Oriolev', 'titular'),
  (27, 'Evgeni', 'titular'),
  (27, 'Gazalov', 'titular'),
  (27, 'Yuri', 'titular'),
  (27, 'Ladrinskj', 'titular'),
  (27, 'Machin', 'titular'),
  (27, 'Alvarezko', 'titular'),
  (27, 'Teleskov', 'titular'),
  (27, 'Stefanov', 'titular'),
  (27, 'Vinyalovic', 'titular'),
  (27, 'Ricky', 'titular'),
  (28, 'Danilov', 'titular'),
  (28, 'Evgeni', 'titular'),
  (28, 'Gazalov', 'titular'),
  (28, 'Jasha', 'titular'),
  (28, 'Yuri', 'titular'),
  (28, 'Ladrinskj', 'titular'),
  (28, 'Germanov', 'titular'),
  (28, 'Alvarezko', 'titular'),
  (28, 'Teleskov', 'titular'),
  (28, 'Ricky', 'titular'),
  (28, 'Davidov', 'titular'),
  (29, 'Adrianskj', 'titular'),
  (29, 'Danilov', 'titular'),
  (29, 'Oriolev', 'titular'),
  (29, 'Yuri', 'titular'),
  (29, 'Ladrinskj', 'titular'),
  (29, 'Machin', 'titular'),
  (29, 'Germanov', 'titular'),
  (29, 'Alvarezko', 'titular'),
  (29, 'Teleskov', 'titular'),
  (29, 'Stefanov', 'titular'),
  (29, 'Ricky', 'titular'),
  (29, 'Xavi', 'titular'),
  (29, 'Gazalov', 'reserva'),
  (30, 'Adrianskj', 'titular'),
  (30, 'Danilov', 'titular'),
  (30, 'Oriolev', 'titular'),
  (30, 'Gazalov', 'titular'),
  (30, 'Jasha', 'titular'),
  (30, 'Yuri', 'titular'),
  (30, 'Ladrinskj', 'titular'),
  (30, 'Machin', 'titular'),
  (30, 'Teleskov', 'titular'),
  (30, 'Vinyalovic', 'titular'),
  (30, 'Ricky', 'titular'),
  (30, 'Xavi', 'titular'),
  (30, 'Evgeni', 'reserva'),
  (30, 'Alvarezko', 'reserva'),
  (30, 'Stefanov', 'reserva'),
  (31, 'Adrianskj', 'titular'),
  (31, 'Santiagovitx', 'titular'),
  (31, 'Danilov', 'titular'),
  (31, 'Oriolev', 'titular'),
  (31, 'Gazalov', 'titular'),
  (31, 'Yuri', 'titular'),
  (31, 'Ladrinskj', 'titular'),
  (31, 'Germanov', 'titular'),
  (31, 'Teleskov', 'titular'),
  (31, 'Stefanov', 'titular'),
  (31, 'Mijailichenko', 'titular'),
  (31, 'Vinyalovic', 'titular'),
  (31, 'Ricky', 'reserva'),
  (31, 'Xavi', 'reserva'),
  (32, 'Adrianskj', 'titular'),
  (32, 'Santiagovitx', 'titular'),
  (32, 'Danilov', 'titular'),
  (32, 'Gazalov', 'titular'),
  (32, 'Yuri', 'titular'),
  (32, 'Machin', 'titular'),
  (32, 'Teleskov', 'titular'),
  (32, 'Stefanov', 'titular'),
  (32, 'Mijailichenko', 'titular'),
  (32, 'Vinyalovic', 'titular'),
  (32, 'Davidov', 'titular'),
  (32, 'Xavi', 'titular'),
  (32, 'Oriolev', 'reserva'),
  (32, 'Jasha', 'reserva'),
  (32, 'Ladrinskj', 'reserva'),
  (33, 'Adrianskj', 'titular'),
  (33, 'Danilov', 'titular'),
  (33, 'Yuri', 'titular'),
  (33, 'Ladrinskj', 'titular'),
  (33, 'Machin', 'titular'),
  (33, 'Germanov', 'titular'),
  (33, 'Alvarezko', 'titular'),
  (33, 'Teleskov', 'titular'),
  (33, 'Stefanov', 'titular'),
  (33, 'Vinyalovic', 'titular'),
  (33, 'Ricky', 'titular'),
  (33, 'Xavi', 'titular'),
  (33, 'Mijailichenko', 'reserva'),
  (34, 'Adrianskj', 'titular'),
  (34, 'Santiagovitx', 'titular'),
  (34, 'Danilov', 'titular'),
  (34, 'Oriolev', 'titular'),
  (34, 'Gazalov', 'titular'),
  (34, 'Jasha', 'titular'),
  (34, 'Yuri', 'titular'),
  (34, 'Ladrinskj', 'titular'),
  (34, 'Stefanov', 'titular'),
  (34, 'Vinyalovic', 'titular'),
  (34, 'Ricky', 'titular'),
  (34, 'Xavi', 'titular'),
  (35, 'Adrianskj', 'titular'),
  (35, 'Danilov', 'titular'),
  (35, 'Oriolev', 'titular'),
  (35, 'Evgeni', 'titular'),
  (35, 'Jasha', 'titular'),
  (35, 'Yuri', 'titular'),
  (35, 'Ladrinskj', 'titular'),
  (35, 'Machin', 'titular'),
  (35, 'Alvarezko', 'titular'),
  (35, 'Teleskov', 'titular'),
  (35, 'Vinyalovic', 'titular'),
  (35, 'Ricky', 'titular'),
  (35, 'Santiagovitx', 'reserva'),
  (36, 'Santiagovitx', 'titular'),
  (36, 'Oriolev', 'titular'),
  (36, 'Evgeni', 'titular'),
  (36, 'Gazalov', 'titular'),
  (36, 'Ladrinskj', 'titular'),
  (36, 'Machin', 'titular'),
  (36, 'Germanov', 'titular'),
  (36, 'Alvarezko', 'titular'),
  (36, 'Teleskov', 'titular'),
  (36, 'Stefanov', 'titular'),
  (36, 'Vinyalovic', 'titular'),
  (36, 'Xavi', 'titular'),
  (36, 'Adrianskj', 'reserva'),
  (36, 'Danilov', 'reserva'),
  (36, 'Jasha', 'reserva'),
  (37, 'Adrianskj', 'titular'),
  (37, 'Santiagovitx', 'titular'),
  (37, 'Danilov', 'titular'),
  (37, 'Evgeni', 'titular'),
  (37, 'Jasha', 'titular'),
  (37, 'Yuri', 'titular'),
  (37, 'Ladrinskj', 'titular'),
  (37, 'Machin', 'titular'),
  (37, 'Germanov', 'titular'),
  (37, 'Stefanov', 'titular'),
  (37, 'Ricky', 'titular'),
  (37, 'Davidov', 'titular'),
  (38, 'Santiagovitx', 'titular'),
  (38, 'Danilov', 'titular'),
  (38, 'Evgeni', 'titular'),
  (38, 'Gazalov', 'titular'),
  (38, 'Jasha', 'titular'),
  (38, 'Yuri', 'titular'),
  (38, 'Ladrinskj', 'titular'),
  (38, 'Teleskov', 'titular'),
  (38, 'Stefanov', 'titular'),
  (38, 'Mijailichenko', 'titular'),
  (38, 'Ricky', 'titular'),
  (38, 'Xavi', 'titular'),
  (38, 'Machin', 'reserva'),
  (38, 'Germanov', 'reserva'),
  (39, 'Adrianskj', 'titular'),
  (39, 'Santiagovitx', 'titular'),
  (39, 'Gazalov', 'titular'),
  (39, 'Jasha', 'titular'),
  (39, 'Yuri', 'titular'),
  (39, 'Ladrinskj', 'titular'),
  (39, 'Machin', 'titular'),
  (39, 'Germanov', 'titular'),
  (39, 'Stefanov', 'titular'),
  (39, 'Ricky', 'titular'),
  (39, 'Xavi', 'titular'),
  (39, 'Amigos', 'titular'),
  (39, 'Teleskov', 'reserva'),
  (40, 'Adrianskj', 'titular'),
  (40, 'Santiagovitx', 'titular'),
  (40, 'Danilov', 'titular'),
  (40, 'Gazalov', 'titular'),
  (40, 'Yuri', 'titular'),
  (40, 'Ladrinskj', 'titular'),
  (40, 'Machin', 'titular'),
  (40, 'Germanov', 'titular'),
  (40, 'Alvarezko', 'titular'),
  (40, 'Stefanov', 'titular'),
  (40, 'Vinyalovic', 'titular'),
  (40, 'Ricky', 'titular'),
  (41, 'Adrianskj', 'titular'),
  (41, 'Danilov', 'titular'),
  (41, 'Oriolev', 'titular'),
  (41, 'Jasha', 'titular'),
  (41, 'Yuri', 'titular'),
  (41, 'Ladrinskj', 'titular'),
  (41, 'Machin', 'titular'),
  (41, 'Germanov', 'titular'),
  (41, 'Teleskov', 'titular'),
  (41, 'Vinyalovic', 'titular'),
  (41, 'Ricky', 'titular'),
  (41, 'Xavi', 'titular'),
  (42, 'Adrianskj', 'titular'),
  (42, 'Danilov', 'titular'),
  (42, 'Evgeni', 'titular'),
  (42, 'Gazalov', 'titular'),
  (42, 'Jasha', 'titular'),
  (42, 'Yuri', 'titular'),
  (42, 'Ladrinskj', 'titular'),
  (42, 'Machin', 'titular'),
  (42, 'Teleskov', 'titular'),
  (42, 'Vinyalovic', 'titular'),
  (42, 'Ricky', 'titular'),
  (42, 'Xavi', 'titular'),
  (43, 'Adrianskj', 'titular'),
  (43, 'Danilov', 'titular'),
  (43, 'Evgeni', 'titular'),
  (43, 'Gazalov', 'titular'),
  (43, 'Jasha', 'titular'),
  (43, 'Yuri', 'titular'),
  (43, 'Ladrinskj', 'titular'),
  (43, 'Machin', 'titular'),
  (43, 'Teleskov', 'titular'),
  (43, 'Vinyalovic', 'titular'),
  (43, 'Ricky', 'titular'),
  (43, 'Xavi', 'titular')
) as v(jornada, nombre, rol)
join temporadas t on t.nombre = '2025/26'
join jornadas jo on jo.temporada_id = t.id and jo.numero = v.jornada
join jugadores ju on ju.nombre = v.nombre;

commit;
